########## Dataset configuration ##########
[dataset]
type = "bird"
split = "dev"
root_path = "data/bird"
save_path = "workspace/dataset/bird/dev.pkl"

########## Vector database configuration ##########
[vector_database]
embedding_model_name_or_path = "Qwen/Qwen3-Embedding-0.6B"
use_qwen3_embedding = true
local_files_only = false
normalize_embeddings = false
store_root_path = "workspace/vector_database/bird/dev"
max_value_length = 100
lower_meta_data = true

########## Value retrieval configuration ##########
[value_retrieval]
n_results = 5
n_parallel = 16
save_path = "workspace/value_retrieval/bird/dev.pkl"

[value_retrieval.llm]
model = "Qwen3-Coder-30B-A3B-Instruct"
base_url = "http://0.0.0.0:8000/v1"
api_key = "dummy"
max_tokens = 4096
temperature = 0.7
api_type = "openai"

########## Schema linking configuration ##########
[schema_linking]
n_parallel = 16
save_path = "workspace/schema_linking/bird/dev.pkl"
direct_linking_sampling_budget = 8
reversed_linking_sampling_budget = 8
value_distance_threshold = 0.02

[schema_linking.llm]
model = "Qwen3-Coder-30B-A3B-Instruct"
base_url = "http://0.0.0.0:8000/v1"
api_key = "dummy"
max_tokens = 4096
temperature = 0.7
api_type = "openai"

########## SQL generation configuration ##########
[sql_generation]
n_parallel = 16
save_path = "workspace/sql_generation/bird/dev.pkl"
dc_sampling_budget = 8
skeleton_sampling_budget = 8
icl_sampling_budget = 8
icl_few_shot_examples_path = "data/bird/dev/few_shots.json"

[sql_generation.llm]
model = "Qwen3-Coder-30B-A3B-Instruct"
base_url = "http://0.0.0.0:8000/v1"
api_key = "dummy"
max_tokens = 4096
temperature = 0.7
api_type = "openai"

########## SQL revision configuration ##########
[sql_revision]
n_parallel = 16
save_path = "workspace/sql_revision/bird/dev.pkl"
checker_sampling_budget = 5

[sql_revision.llm]
model = "Qwen3-Coder-30B-A3B-Instruct"
base_url = "http://0.0.0.0:8000/v1"
api_key = "dummy"
max_tokens = 4096
temperature = 0.7
api_type = "openai"

########## SQL selection configuration ##########
[sql_selection]
n_parallel = 16
save_path = "workspace/sql_selection/bird/dev.pkl"
filter_top_k_sql = 2
evaluator_sampling_budget = 16
shortcut_consistency_score_threshold = 0.6

[sql_selection.llm]
model = "Qwen3-Coder-30B-A3B-Instruct"
base_url = "http://0.0.0.0:8000/v1"
api_key = "dummy"
max_tokens = 4096
temperature = 0.7
api_type = "openai"
